
CC=g++
CFLAGS=-c -Wall

problem1: problem1
	$(CC) $(CFLAGS) problem1.c -o problem1

problem2: problem2
	$(CC) $(CFLAGS) problem2.c -o problem2

problem3: problem3
	$(CC) $(CFLAGS) -lm problem3.c -o problem3 
	
problem4: problem4
	$(CC) $(CFLAGS) problem4.c -o problem4 

all: problem1 problem2 problem3 problem4


clean:
	rm problem1 problem2 problem3 problem4