// Problem 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of 
//the even-valued terms.


#include <stdio.h>


int fibsum(int max)
{
   int current= 1;
   int last = 0;
   int sum = 0;
   int tmp;

   while(current < max)
   {
      if((current % 2) == 0)
      {
         sum += current;     
      }

      tmp = current;
      current += last;
      last = tmp;
   }
  
   return(sum);  
}



int main(void)
{
   //debug (2 lines)
   //printf("The sum of the even terms of the fibonacci sequence below 10 is %d\n", fibsum(10));  
   //printf("The sum of the even terms of the fibonacci sequence below 50 is %d\n", fibsum(50));  

   printf("The sum of the even terms of the fibonacci sequence below 4000 000 is %d\n", fibsum(4000000));  
   return(0);
}

